spring:
  application:
    name: demo

#  config:
#    import:
#      - "tenants/tenants.yaml"

  docker:
    compose:
      enabled: true

  datasource-master:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
  #    open-in-view: false

  sql:
    init:
      platform: mysql
      schema-locations:
      - "classpath:sql/mysql/schema.sql"
      data-locations:
      - "classpath:sql/mysql/data.sql"
      mode: never

#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#              create-source: metadata

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    baseline-version: 1
#    url: jdbc:mysql://localhost:3306/test
#    user: root
#    password: root

default-tenant: test

multitenancy:
  tenants:
    - name: tenant1
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tenant1
        username: root
        password: root
    - name: tenant2
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tenant2
        username: root
        password: root
    - name: test
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root